openapi: 3.0.3
info:
  title: ID Contact Authentication plugin
  description: >
    ID Contact Authentication plugin. Given an AttributeRequest, 
    it manages the authentication and disclosure flow with the citizen,
    which results in a signed set of attributes corresponding to the
    AttributeRequest.
  contact:
    email: henkdieter@tweedegolf.com
  version: 0.0.1
externalDocs:
  description: Repository
  url: 'https://tgrep.nl/id-contact/id-contact/'
servers:
  - url: 'https://auth.idcontact.test.tweede.golf'
    description: Local development
tags:
  - name: Authentication
security:
  - BasicAuth: []

paths:
  /start_authentication:
    post:
      tags:
        - Authentication
      description: Start an authentication flow using this plugin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                attributes:
                  type: array
                  items:
                    type: string
                    example: BSN
                  minItems: 1
                  description: List of attributes requested. Attributes are defined per installation, and the plugin is responsible for mapping these to what it can provide.
                attr_url:
                  type: string
                  format: uri
                  example: "https://your.org/core/auth_result?id=1723"
                  description: URL to which authentication result will be sent after completion of authentication flow
                continuation:
                  type: string
                  format: uri
                  example: "https://your.org/widget/select_comm"
                  description: URI to which the client should be redirected after completing the authentication flow.
              required:
                - attributes
                - continuation
      responses:
        '200':
          description: Successfully started request
          content:
            application/json:
              schema:
                type: object
                properties:
                  client_url:
                    type: string
                    format: uri
                    description: URL client can use to start authenticating
                    example: "https://your.org/your_auth/start_auth?sessid=5"
      callbacks:
        attr_url:
          '{$request.body#/result_url}':
            $ref: './shared.openapi.yml#/components/callbacks/attr_url/path'
        continuation:
          '{$request.body#/continuation}':
            $ref: './shared.openapi.yml#/components/callbacks/client_url/path'
        session_url:
          '{$callbacks.attr_url.response.body#/session_url}':
            $ref: './shared.openapi.yml#/components/callbacks/session_url/path'
