openapi: 3.0.3
info:
  title: ID Contact core
  description: ID Contact core. Matches session requests with authentication and communication methods and redirects citizens to corresponding plugins.
  contact:
    email: henkdieter@tweedegolf.com
  version: 0.0.2
externalDocs:
  description: Repository
  url: 'https://tgrep.nl/id-contact/id-contact/'
servers:
  - url: 'https://core.idcontact.test.tweede.golf'
    description: Local development
tags:
  - name: Session
  - name: Authentication
  - name: Communication
security:
  - BasicAuth: []
paths:
  /session:
    post:
      summary: Create a new Session and get details on the required attributes and the possible communication methods. To be called by the widget.
      tags:
        - Session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'components/schemas.yml#/SessionRequest'
      responses:
        '200':
          description: Session created successfully.
          content:
            application/json:
              schema:
                $ref: 'components/schemas.yml#/SessionResponse'
                    
  /authenticate:
    post:
      summary: Select an authentication endpoint and set up the authentication flow. To be called by the widget.
      tags: 
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'components/schemas.yml#/SelectAuthEndpointRequest'
      responses:
        '200':
          description: Authentication flow set up successfully
          content:
            application/json:
              schema:
                $ref: 'components/schemas.yml#/SelectAuthEndpointResponse'
                
  /communicate:
    post:
      summary: Select a communication endpoint and set up the communication flow. To be called by the widget.
      tags:
        - Communication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'components/schemas.yml#/SelectCommEndpointRequest'
      responses:
        '200':
          description: Communication set up successfully.
          content:
            application/json:
              schema:
                $ref: 'components/schemas.yml#/SelectCommEndpointResponse'
        

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic