openapi: 3.0.3
info:
  title: ID Contact core
  description: ID Contact core. Matches session requests with authentication and communication methods and redirects citizens to corresponding plugins.
  contact:
    email: henkdieter@tweedegolf.com
  version: 0.0.3
externalDocs:
  description: Repository
  url: 'https://tgrep.nl/id-contact/id-contact/'
servers:
  - url: 'https://core.idcontact.test.tweede.golf'
    description: Local development
tags:
  - name: Session
security:
  - BasicAuth: []

paths:
  '/session_options/{purpose}':
    get:
      description: Get the available choices for a session given its purpose.
      tags:
        - Session
      parameters:
        - in: path
          name: purpose
          required: true
          schema:
            type: string
          description:
            Purpose for which we want the session options.
      responses:
        '200':
          description: Allowed authentication and communication methods for given purpose
          content:
            application/json:
              schema:
                type: object
                properties:
                  auth_methods:
                    type: array
                    minItems: 1
                    items:
                      type: object
                      properties:
                        tag:
                          type: string
                          description: Tag identifying the authentication method.
                        name:
                          type: string
                          description: Human-readable name of the authentication method.
                      required:
                        - tag
                  comm_methods:
                    type: array
                    minItems: 1
                    items:
                      type: object
                      properties:
                        tag:
                          type: string
                          description: Tag identifying the communication methods.
                        name:
                          type: string
                          description: Human-readable name of the communication method.
                      required:
                        - tag
                required:
                  - auth_methods
                  - comm_methods
  '/start':
    post:
      description: >
        Start a new ID-Contact flow with the requested authentication and
        communication method.
        
        When called without a communication method
        starts just the authentication flow. The results of such a
        authentication-only flow can then be given to a later invocation
        to start a communication session using that identification. For
        such requests, the request body should be the request claim in a
        signed jwt with properly set kid (see core documentation)

        When called without an authentication method it uses the given
        attributes as authentication, or if that is not available, starts
        an unauthenticated communication if allowed for the given purpose.
      tags:
        - Session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                purpose:
                  type: string
                  description: Purpose for the requested flow
                auth_method:
                  type: string
                  description: Tag of the chosen authentication method.
                auth_result:
                  type: string
                  description: JWT containing the results of an earlier authentication session.
                comm_method:
                  type: string
                  description: Tag of the chosen communication method.
                comm_url:
                  type: string
                  format: url
                  description: URL to redirect client to after authentication session for communication (exclusive with comm_method)
                attr_url:
                  type: string
                  format: url
                  description: URL to post authentication results to (only valid in combination with comm_url)
              required:
                - purpose
      responses:
        '200':
          description: Requested flow was succesfully created.
          content:
            application/json:
              schema:
                type: object
                properties:
                  client_url:
                    type: string
                    format: url
                    description: URL to redirect client to to start requested flow.
                required:
                  - client_url
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
