openapi: 3.0.3
info:
  title: ID Contact Matcher
  description: ID Contact Matcher. Manages a pool of KCC agents to which sessions are assigned using a queue that is common to all communication methods.
  contact:
    email: henkdieter@tweedegolf.com
  version: 0.0.1
externalDocs:
  description: Repository
  url: 'https://tgrep.nl/id-contact/id-contact/'
servers:
  - url: 'https://core.idcontact.test.tweede.golf'
    description: Local development
tags:
  - name: Assginment
security:
  - BasicAuth: []
paths:
  /assign:
    post:
      summary: Get the ID of the agent that is to be assigned to the session. To be called by the comm plugin.
      tags:
        - Assignment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'components/schemas.yml#/Session'
      responses:
        '200':
          description: Placed in queue
          content:
            application/json:
              schema:
                properties:
                  officialId:
                    type: string
  
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic