openapi: 3.0.3
info:
  title: ID Contact core
  description: ID Contact core. Matches session requests with authentication and communication methods and redirects citizens to corresponding plugins. Also, manages a pool of KCC-officials to which sessions are assigned using a queue that is common to all communication methods.
  contact:
    email: henkdieter@tweedegolf.com
  version: 0.0.1
externalDocs:
  description: Repository
  url: 'https://tgrep.nl/id-contact/id-contact/'
servers:
  - url: 'https://core.idcontact.test.tweede.golf'
    description: Local development
tags:
  - name: Session
security:
  - BasicAuth: []
paths:
  /session:
    post:
      summary: Create a new Session and get details on the required attributes and the possible communication methods. To be called by the client.
      tags:
        - Session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'components/schemas.yml#/SessionRequest'
      responses:
        '200':
          description: Session created
          content:
            application/json:
              schema:
                properties:
                  session:
                    $ref: 'components/schemas.yml#/Session'
                  attrRequests:
                    type: array
                    items: 
                      $ref: 'components/schemas.yml#/AttributeRequest'
                  commEndpoints:
                    type: array
                    items:
                      type: string
  
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic