@startuml
title ID-contact Core Global deployment v0.2
skinparam rectangle {
    roundCorner<<Auth plugin>> 25
}

skinparam rectangle {
    roundCorner<<Comm plugin>> 10
}

actor Citizen as citizen
actor Agent as agent

cloud "ID contact" {
    rectangle Core as core
    rectangle "IRMA" <<Auth plugin>> as auth_irma
    rectangle "DigiD Routeringsvoorziening" <<Auth plugin>> as auth_digid

    rectangle "Amazon Connect" <<Comm plugin>> as comm_connect
    rectangle "Matrix" <<Comm plugin>> as comm_matrix

    rectangle "Matcher" <<Optional>> as matcher
    database "Session database" as session_db
}

rectangle Widget as widget
rectangle "Matrix Client" as matrix_client
rectangle "Connect client" as connect_client
rectangle IRMA as irma
rectangle DigiD as digid


citizen<-->widget
citizen<-->irma
citizen<-->digid
agent<-->connect_client
agent<-->matrix_client

core<-u->widget
core<->auth_digid
core<->auth_irma
core<-l->comm_matrix
core<-l->comm_connect

core<-->session_db

digid<-->auth_digid
irma<-->auth_irma

matrix_client<-->comm_matrix
connect_client<-->comm_connect

comm_connect<..>matcher
comm_matrix<..>matcher

@enduml