
@startuml
title ID-contact Core Global sequence with split choice v0.3.0

actor Citizen as citizen
participant "Core widget" as widget
participant "ID Contact Core" as core
participant "Auth plugin" as auth_plugin
participant "Auth widget" as auth_widget
participant "Comm plugin" as comm_plugin
participant "Comm widget" as comm_widget
actor Agent as agent

== Initialize session ==

activate citizen
citizen->widget: navigate
activate widget
widget-->citizen: page
citizen->widget: click
widget->core: sessionOptions(purpose)
activate core
core->core: getAuthMethods(purpose)
core->core: getCommMethods(purpose)
core-->widget: ok(commMethods, authMethods),
deactivate core
widget-->citizen: authMethods

== Choose authentication == 

citizen->widget: selectAuthMethod
citizen->widget: start
widget->core: start(authMethod, purpose)
activate core
core->core: getAttrRequest(purpose)
core->auth_plugin: start(clientRedirect=conf.widgetUrl(purpose), attrRequest)
activate auth_plugin
auth_plugin-->core: ok(authUrl)
core-->widget: redirect(authUrl)
deactivate core
widget-->citizen: redirect(authUrl)
deactivate widget

== Authentication ==

citizen->auth_widget: load(authUrl)
activate auth_widget
auth_widget-->citizen: page
deactivate auth_widget

citizen->auth_plugin: authenticate
auth_plugin-->citizen: redirect(clientRedirect(attrsEncrypted))
deactivate auth_plugin

== Choose communication ==

citizen->widget: load(widgetUrl(purpose, attrsEncrypted))
activate widget
widget-->citizen: page
widget->core: sessionOptions(purpose)
activate core
core->core: getAuthMethods(purpose)
core->core: getCommMethods(purpose)
core-->widget: ok(commMethods, authMethods)
deactivate core
widget-->citizen: commMethods
citizen->widget: selectCommMethod
citizen->widget: start
widget->core: start(commMethod, purpose, attrsEncrypted)
activate core
core->comm_plugin: start(purpose, attrsEncrypted)
activate comm_plugin
comm_plugin-->core: ok(commUrl)
core-->widget: redirect(commUrl)
deactivate core
widget-->citizen: redirect(commUrl)
deactivate widget

== Start conversation ==

citizen->comm_widget: load(commUrl)
activate comm_widget
comm_widget-->citizen: page

citizen->comm_widget: startConversation
comm_widget->comm_plugin: startConversation

comm_plugin->comm_plugin: assignAgent(purpose)
comm_plugin->comm_plugin: createConversation(agentId)

== Conversation ongoing ==
comm_plugin->comm_plugin: decrypt(attrsEncrypted)
comm_plugin->agent: newConversation(attrs)

activate agent
citizen<->agent: conversation

== End conversation ==
agent->comm_plugin: closeConversation
comm_plugin->comm_widget: conversationClosed
deactivate widget
comm_widget->citizen: conversationClosed
deactivate comm_widget
deactivate citizen
agent->comm_plugin: deleteAttributes
comm_plugin->agent: ok
deactivate comm_plugin
deactivate agent


@enduml
